fix(cart): a null shipping total should be null instead of zero
graycoreio/daffodil pull request #1071
Opened 2020-09-21 19:28 UTC by lderrickable

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
The shipping total in daffodil is set to zero even if the total from magento is null. This is a problem, because the shipping total needs to be shown as "FREE" when the shipping total is zero. So the shipping will be shown as "FREE" even though a shipping method hasn't been chosen yet.

## What is the new behavior?
The shipping total will be null when the shipping method hasn't been chosen yet.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2020-09-21 19:51 UTC, griest024 submitted a review, later dismissed

2020-09-21 20:00 UTC, damienwebdev requested changes
Would it be better to instead return an empty object for the total, and then throw an error here? A null total is a bit odd, I'd anticipate it being numeric.

2020-09-21 22:38 UTC, lderrickable commented
I don't think so. Because we'd be throwing an error any time that there is no shipping method defined. I think it makes sense for the shipping total to be numeric or null, because a value of zero is not the same as it not being provided. In other words, we don't have a way to differentiate between no shipping method selected and "Free Shipping". Actually, I think tax should be handled this way too, because we don't currently have a way to differentiate between no tax and zero tax either.

2020-09-22 03:12 UTC, damienwebdev commented
Needs docs, but I'm fine with the behavior.

2020-09-22 14:31 UTC, lderrickable commented
added docs

2020-09-22 16:41 UTC, griest024 approved these changes

2020-09-22 17:05 UTC, damienwebdev approved these changes
lgtm

2020-09-22 17:05 UTC, merged