feat(product): add selectors for product prices and discounted prices
graycoreio/daffodil pull request #1177
Opened 2020-12-04 20:13 UTC by lderrickable

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Adds selectors for product prices and discounted prices (meant to be used for simple products).

2020-12-05 18:34 UTC, griest024 requested changes

2020-12-05 18:34 UTC, griest024 commented on libs/product/src/selectors/product-entities/product-entities.selectors.ts
> +			return product && product.price || null;
Optional chaining todo

2020-12-06 06:07 UTC, lderrickable commented on libs/product/src/selectors/product-entities/product-entities.selectors.ts
> +			return product && product.price || null;
added

2020-12-06 06:07 UTC, griest024 approved these changes

2020-12-06 06:50 UTC, merged