feat(cart): add selector for total cart items
graycoreio/daffodil pull request #1178
Opened 2020-12-04 23:13 UTC by lderrickable

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?
Adds a selector and facade field for the total number of cart items, taking into account the quantity of each cart item.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2020-12-05 18:41 UTC, griest024 requested changes

2020-12-05 18:41 UTC, griest024 commented on libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.ts
> +			}, 0)
Can you make this a lambda?

2020-12-06 06:05 UTC, lderrickable commented on libs/cart/state/src/selectors/cart-item-entities/cart-item-entities.selectors.ts
> +			}, 0)
done

2020-12-06 06:06 UTC, griest024 approved these changes

2020-12-06 06:50 UTC, merged