feat(external-router): add new external routing package scaffold
graycoreio/daffodil pull request #1216
Opened 2021-01-11 18:37 UTC by damienwebdev

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
We don't have a package that allows us to wire up an external router.

Fixes: N/A

## What is the new behavior?
This will be the beginning of the new package.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2021-01-11 23:04 UTC, griest024 requested changes

2021-01-11 23:04 UTC, griest024 commented on libs/external-router/README.md
> +This package serves to allow developers using Angular to wire an external router into their client-side routing mechanism.
Maybe `aims` instead of `serves`?

2021-01-12 20:00 UTC, lderrickable commented on libs/external-router/README.md
> +This package serves to allow developers using Angular to wire an external router into their client-side routing mechanism.
Or just "allows"

2021-01-12 20:10 UTC, damienwebdev commented on libs/external-router/README.md
> +This package serves to allow developers using Angular to wire an external router into their client-side routing mechanism.
6dce684f

2021-01-12 20:11 UTC, griest024 approved these changes

2021-01-13 14:51 UTC, merged