Ng10 2
graycoreio/daffodil pull request #1229
Opened 2021-01-12 14:58 UTC by griest024

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2021-01-12 20:43 UTC, griest024 commented
/azp run

2021-01-15 18:16 UTC, lderrickable requested changes

2021-01-15 21:14 UTC, griest024 commented on apps/demo/src/app/product/pages/product-grid-view/product-grid-view.component.spec.ts
> +        DaffCartTestingModule
good catch, removed

2021-01-16 00:51 UTC, lderrickable commented
lgtm

2021-01-16 00:51 UTC, lderrickable approved these changes

2021-01-20 22:28 UTC, damienwebdev commented
Merged manually.

2021-01-20 22:28 UTC, closed without merging