feat(category): move page actions to  and
graycoreio/daffodil pull request #1310
Opened 2021-03-03 17:35 UTC by damienwebdev

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2021-03-03 19:08 UTC, griest024 approved these changes

2021-03-03 23:38 UTC, damienwebdev commented
needs @lderrickable review

2021-03-04 15:07 UTC, lderrickable requested changes
lgtm. Waiting on @damienwebdev 's approval of the eslint PR to avoid conflicts.

2021-03-04 19:51 UTC, damienwebdev commented
@lderrickable rebased.

2021-03-04 21:46 UTC, lderrickable approved these changes

2021-03-04 21:49 UTC, merged