feat(core, product): rename DaffSortable to DaffOrderable
graycoreio/daffodil pull request #1323
Opened 2021-03-08 14:56 UTC by damienwebdev

BREAKING CHANGE: the interface name changed, the above swap is sufficient to breakfix.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently, we have an existing interface called "DaffSortable". This name will collide with the refactor on-going in DaffCategory. 

Fixes: N/A

## What is the new behavior?
In order to prevent the collision, I'm proposing "DaffOrderable" instead.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

2021-03-08 20:27 UTC, griest024 requested changes

2021-03-08 20:27 UTC, griest024 commented on libs/core/src/orderable/orderable.ts
> + * Disambiguation: This is does not relate to ecommerce "Orders", e.g.a purchase.
missing space after `e.g.`

2021-03-08 23:03 UTC, lderrickable commented
What does `DaffSortable` collide with in the category refactor? 

`Orderable` seems a little ambiguous in an e-commerce library, because it could mean that you can buy it or that you can sort it. So I think "sortable" is preferable, but I don't know what the particular collision is.

2021-03-08 23:24 UTC, lderrickable commented
The only alternative I can think of is `DaffPositioned` with the field being `position` rather than `order`. I think I actually like `DaffOrderable` better with the disambiguity comment though

2021-03-09 13:55 UTC, damienwebdev commented on libs/core/src/orderable/orderable.ts
> + * Disambiguation: This is does not relate to ecommerce "Orders", e.g.a purchase.
13ac9d76

2021-03-09 13:56 UTC, griest024 approved these changes

2021-03-09 14:22 UTC, merged