feat(category): replace DaffCategorySortOption with DaffSortOption from core.
graycoreio/daffodil pull request #1363
Opened 2021-03-16 19:39 UTC by damienwebdev

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Currently, we rely on a special type of category that is no longer necessary.

Fixes: N/A

## What is the new behavior?
We now have a defined type in core that we use here.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2021-03-17 00:40 UTC, griest024 submitted a review, later dismissed

2021-03-17 00:41 UTC, griest024 requested changes
You forgot to replace it in one of the models

2021-03-18 14:00 UTC, damienwebdev commented
@griest024 resolved.

2021-03-18 15:55 UTC, griest024 approved these changes

2021-03-18 17:04 UTC, merged