docs(all): reorganize guides content
graycoreio/daffodil pull request #1565
Opened 2021-05-28 21:20 UTC by lderrickable

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
The directory structure for the markdown files of each package aren't organized the way daff.io expects.

## What is the new behavior?
Changed the directory structure to be shallower. Almost all changes are just moving text into different files, but I made some minor changes like removing some links that won't work. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2021-06-04 01:40 UTC, griest024 requested changes

2021-06-04 01:40 UTC, griest024 commented on libs/category/guides/filtering.md
> +Daffodil applies filters "idempotently". That is to say, when a filter operation is applied multiple times, the returned result is guaranteed the be the same.
guaranteed ~~the~~ to be the same

2021-06-04 14:55 UTC, lderrickable commented on libs/category/guides/filtering.md
> +Daffodil applies filters "idempotently". That is to say, when a filter operation is applied multiple times, the returned result is guaranteed the be the same.
fixed

2021-06-04 14:57 UTC, griest024 approved these changes

2021-06-29 14:30 UTC, xelaint approved these changes
lgtm

2021-06-29 19:34 UTC, merged