feat(newsletter): add root state slice interface
graycoreio/daffodil pull request #1610
Opened 2021-06-18 15:33 UTC by griest024

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

#1595

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

selector types have changed

## Other information

2021-06-18 21:21 UTC, lderrickable commented
What made you think to add this feature?

2021-06-18 21:25 UTC, damienwebdev requested changes

2021-06-18 21:25 UTC, damienwebdev commented on libs/newsletter/state/src/reducers/newsletter.reducer.ts
> +export interface DaffContactStateRootSlice {
The slice name is a copy paste error.

2021-06-19 02:19 UTC, griest024 commented on libs/newsletter/state/src/reducers/newsletter.reducer.ts
> +export interface DaffContactStateRootSlice {
fixed

2021-06-19 02:20 UTC, griest024 commented
> What made you think to add this feature?

I prefer to type things as strictly as possible. Adding these types to the selectors created a lot of type errors elsewhere in the codebase that wouldn't have otherwise shown up. `Record<string, any>` is a BS type, though it was at least better than `object`.

2021-06-20 14:31 UTC, damienwebdev approved these changes
lgtm

2021-06-20 14:31 UTC, merged