feat(navigation): add root state slice interface
graycoreio/daffodil pull request #1612
Opened 2021-06-18 15:35 UTC by griest024

BREAKING CHANGES: selector types have changed

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

#1595

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

selector types have changed

## Other information

2021-06-20 19:54 UTC, damienwebdev requested changes

2021-06-20 19:54 UTC, damienwebdev commented on libs/navigation/state/src/facades/navigation.facade.spec.ts
> +  let store: Store<Partial<DaffNavigationStateRootSlice<DaffNavigationTree>>>;
We don't need the partial here.

2021-06-21 14:53 UTC, griest024 commented on libs/navigation/state/src/facades/navigation.facade.spec.ts
> +  let store: Store<Partial<DaffNavigationStateRootSlice<DaffNavigationTree>>>;
removed

2021-06-21 15:32 UTC, damienwebdev approved these changes

2021-06-21 15:32 UTC, merged