feat(product): add support for extra product fragments for Magento
graycoreio/daffodil pull request #1665
Opened 2021-07-06 14:18 UTC by griest024

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?
Adds support for extra product fragments in Magento driver

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2021-07-08 14:10 UTC, lderrickable requested changes

2021-07-08 16:16 UTC, griest024 commented on libs/product/driver/magento/src/injection-tokens/fragments/product.token.ts
> + * An multi-provider injection token for providing extra GraphQL fragments that will be spread into product queries.
fixed

2021-07-08 16:17 UTC, griest024 commented on libs/product/driver/magento/src/injection-tokens/fragments/product.token.ts
> + * The data will appear in DaffCart#extra_attributes.
removed this line entirely beacuse `extra_attributes` shouldn't be necessary with injectable transforms

2021-07-08 18:02 UTC, lderrickable commented on libs/product/driver/magento/src/injection-tokens/fragments/product.token.ts
> + * The data will appear in DaffCart#extra_attributes.
But the injectable transforms is the other PR, right?

2021-07-08 18:05 UTC, griest024 commented on libs/product/driver/magento/src/injection-tokens/fragments/product.token.ts
> + * The data will appear in DaffCart#extra_attributes.
yeah. `DaffProduct` doesn't have an `extra_attributes` field though so this line doesn't apply anayway

2021-07-08 20:22 UTC, lderrickable commented on libs/product/driver/magento/src/injection-tokens/fragments/product.token.ts
> + * The data will appear in DaffCart#extra_attributes.
doesn't it need an `extra_attributes` field? Otherwise, how will we access the fields retrieved through the extra product fragment?

2021-07-08 20:44 UTC, lderrickable commented on libs/product/driver/magento/src/injection-tokens/fragments/product.token.ts
> + * The data will appear in DaffCart#extra_attributes.
> removed this line entirely beacuse `extra_attributes` shouldn't be necessary with injectable transforms

Oh. I just understood what you meant here. lgtm

2021-07-08 20:47 UTC, lderrickable commented
lgtm

2021-07-09 13:19 UTC, lderrickable approved these changes

2021-07-09 13:19 UTC, merged