feat(design): media gallery fixes
graycoreio/daffodil pull request #1668
Opened 2021-07-06 18:01 UTC by xelaint

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2021-07-07 13:34 UTC, damienwebdev requested changes

2021-07-07 13:34 UTC, damienwebdev commented on libs/design/src/molecules/media-gallery/media-gallery.component.ts
> +	}
I think we should similarly remove the registry onDestroy too.

2021-07-09 17:06 UTC, xelaint commented
@lderrickable can you please help me write tests for the updates I just made in the `temp` commit?

2021-07-19 15:28 UTC, lderrickable commented
> @lderrickable can you please help me write tests for the updates I just made in the `temp` commit?

added

2021-11-17 12:14 UTC, damienwebdev approved these changes
lgtm

2021-11-17 12:14 UTC, merged