feat(design): create decorative icon component
graycoreio/daffodil pull request #1784
Opened 2021-08-30 20:45 UTC by xelaint

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
There is no component to centralize a 'decorative' icon used for visual or branding reinforcement.

Fixes: N/A

## What is the new behavior?
Create a component that can be used as decorative icon, separate from the icon button, which has semantic meaning. 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2021-09-14 00:36 UTC, griest024 requested changes

2021-09-14 00:36 UTC, griest024 commented on libs/design/src/atoms/decorative-icon/README.md
> +`DaffIconComponent` is a basic
This seems incomplete.

2021-09-14 00:36 UTC, griest024 commented on libs/design/src/atoms/decorative-icon/README.md
> +</daff-container>
This doesn't apply to the icon component.

2024-07-23 16:11 UTC, xelaint commented
stale

2024-07-23 16:11 UTC, closed without merging