feat(product): add kind and extension factories
graycoreio/daffodil pull request #1785
Opened 2021-09-01 13:53 UTC by griest024

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Product factory injection tokens are not used by the product factories.

## What is the new behavior?
- Adds the product kind factory for creating different product types (composite, configurable, etc.)
- Adds the product extension factory for creating full product data of different kinds
- Renames the `DaffProductFactory` to `DaffDefaultProductFactory`, although the class is still aliased to its original name in `public_api`

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2021-09-09 15:22 UTC, damienwebdev requested changes

2021-09-09 15:42 UTC, griest024 commented on libs/product/testing/src/factories/default-product.factory.ts
> +export class DaffDefaultProductFactory extends DaffModelFactory<DaffProduct> {
improved the docs

2021-09-09 15:43 UTC, griest024 commented on libs/product/testing/src/factories/extension.factory.ts
> + * Factory for creating DaffProducts.
improved

2021-09-10 17:59 UTC, griest024 commented
/azp run

2021-09-10 18:29 UTC, merged