feat(category): pull `current_page` request field from query params
graycoreio/daffodil pull request #1831
Opened 2021-09-17 15:51 UTC by griest024

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: #1829 

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2021-09-28 22:47 UTC, damienwebdev requested changes

2021-09-28 22:47 UTC, damienwebdev commented on libs/category/routing/src/resolvers/category-page-url/category-page-url.resolver.ts
> +    console.log(route.queryParams.p);
Log

2021-09-28 22:48 UTC, griest024 commented on libs/category/routing/src/resolvers/category-page-url/category-page-url.resolver.ts
> +    console.log(route.queryParams.p);
removed

2021-09-29 00:37 UTC, damienwebdev approved these changes

2021-09-29 00:37 UTC, merged