fix(core): guard against divide by 0, Infinity, and NaN in `daffDivide`
graycoreio/daffodil pull request #1845
Opened 2021-09-29 21:08 UTC by griest024

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: #1844 

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2021-09-29 23:49 UTC, damienwebdev requested changes

2021-09-29 23:49 UTC, damienwebdev commented on libs/core/src/utils/long-arithmetic.spec.ts
> +      expect(daffDivide(1, Infinity)).toEqual(NaN);
This first case should return `0`.

2021-09-29 23:49 UTC, damienwebdev commented on libs/core/src/utils/long-arithmetic.spec.ts
> +      expect(daffDivide(Infinity, 1)).toEqual(NaN);
This should return `Infinity`

2021-10-01 04:09 UTC, griest024 commented on libs/core/src/utils/long-arithmetic.spec.ts
> +      expect(daffDivide(1, Infinity)).toEqual(NaN);
changed

2021-10-01 04:09 UTC, griest024 commented on libs/core/src/utils/long-arithmetic.spec.ts
> +      expect(daffDivide(Infinity, 1)).toEqual(NaN);
changed

2021-10-01 20:49 UTC, damienwebdev approved these changes

2021-10-01 20:49 UTC, merged