feat(authorizenet): ensure config is present in Magento driver
graycoreio/daffodil pull request #2008
Opened 2022-03-01 18:22 UTC by griest024

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Required driver config are not validated.

## What is the new behavior?
The Magento driver validates the prescence of required config fields.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2022-03-08 18:43 UTC, damienwebdev requested changes

2022-03-08 18:43 UTC, damienwebdev commented on libs/authorizenet/driver/src/errors/unconfigured.ts
> +export class DaffAuthorizeNeUnconfiguredError extends DaffInheritableError implements DaffError {
There's a typo in the class name.

2022-03-08 23:39 UTC, griest024 commented on libs/authorizenet/driver/src/errors/unconfigured.ts
> +export class DaffAuthorizeNeUnconfiguredError extends DaffInheritableError implements DaffError {
fixed

2022-05-24 03:50 UTC, damienwebdev requested changes

2022-05-24 03:50 UTC, damienwebdev commented on libs/authorizenet/driver/magento/src/authorize-net.service.ts
> +      if (!this.config?.apiLoginID || !this.config?.clientKey) {
Should this be moved to constructor time instead of runtime?

2022-12-05 16:01 UTC, damienwebdev approved these changes

2022-12-05 16:01 UTC, merged