build(all): upgrade to lerna 6
graycoreio/daffodil pull request #2412
Opened 2023-05-03 20:38 UTC by hanmangokiwi

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Building with Lerna does not build in parallel nor take advantage of caching

## What is the new behavior?

Building with Lerna builds in parallel and takes advantage of caching

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2023-05-04 16:35 UTC, damienwebdev requested changes

2023-05-04 16:35 UTC, damienwebdev commented on tools/dgeni/package.json
> -    "@daffodil/docs-utils": "0.0.0-PLACEHOLDER",
Looks like `@daffodil/docs-utils` is a real dependency.

2023-05-04 19:54 UTC, damienwebdev commented
Looks great!

2023-05-04 19:54 UTC, damienwebdev approved these changes

2023-05-04 19:55 UTC, damienwebdev commented
Needs review by @griest024

2023-05-05 00:42 UTC, griest024 approved these changes
<3 Big win!!

2023-05-05 00:54 UTC, merged