Update fragment-introspection.md
graycoreio/daffodil pull request #2463
Opened 2023-06-07 06:50 UTC by shadow0500

Update small patch into the documentation

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2023-06-07 13:22 UTC, damienwebdev requested changes

2023-06-07 13:22 UTC, damienwebdev commented on tools/builders/guides/fragment-introspection.md
> +**In order for Apollo to properly match fragment types, the GraphQL schema must be fetched, processed, added to the codebase, and loaded into the *`ApolloClient`* cache.**
This looks like fluff.

2023-06-07 13:22 UTC, damienwebdev commented on docs/styles.md
> +It's always a good idea to keep child components as modular as possible so they can be reused in different contexts. By having the parent component define the spacing between its child components, yo
I actually like the GPT output here. If you clean this up, I'd accept this PR.

2023-06-08 08:51 UTC, shadow0500 commented on docs/styles.md
> +It's always a good idea to keep child components as modular as possible so they can be reused in different contexts. By having the parent component define the spacing between its child components, yo
Okay , Thank you for your feedback. I am a newbie in open source but I am trying my best to get into it .

2023-06-08 13:18 UTC, damienwebdev commented
Replaced by https://github.com/graycoreio/daffodil/pull/2468

2023-06-08 13:18 UTC, closed without merging