docs: clarify padding guidance in developer docs
graycoreio/daffodil pull request #2468
Opened 2023-06-08 09:07 UTC by shadow0500

Update after cleaning some stuff

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2023-06-08 13:19 UTC, damienwebdev commented
@xelaint can you take a look at this and verify that it looks correct to you?

2023-06-08 14:14 UTC, xelaint commented
@damienwebdev I'm not sure if this doc is necessary to begin with.

2023-06-08 14:19 UTC, damienwebdev commented
I like it, but perhaps its part of a much larger doc describing the "reasoning" behind how we decide on certain styles.

However, are you saying that you think it's no longer relevant?

2023-06-09 05:54 UTC, shadow0500 commented
I am sorry if I did something wrong but I will try my best from the next time and thank you for your feedback.

2023-06-09 14:29 UTC, damienwebdev commented
@shadow0500 no worries! I think the doc here looks good, but I'll let @xelaint decide on what changes should be made.

2023-06-09 14:33 UTC, shadow0500 commented
oh Thankyou , okay I will be waiting for that and look forward to collaborate with you .

2023-06-14 15:07 UTC, xelaint requested changes

2023-06-14 15:07 UTC, xelaint commented on docs/styles.md
> +It's important for child components to not define their own outer padding or margin. This is to make sure that the component can be reused in different parts of an app. Instead, the padding and margi
```suggestion
It's important for individual components to not define their own outer spacing. Components that define their own outer spacing are limited to specific use cases, making it difficult for them to be reusable without overriding their styles with additional CSS. Instead, spacing between components should be handled by the wrapping parent element via the `margin`, `padding`, `gap` or `grid-gap` properties.
```

2023-06-14 15:07 UTC, xelaint commented on docs/styles.md
> +Keeping child components modular ensures that they can be used in different contexts. By having the parent component define the spacing between its child components, you can ensure that the child com
```suggestion
Keeping components modular ensures that they are flexible and extensible. By allowing the parent element to control the spacing for inner elements, individual components will maintain their intended layout regardless of where they are used. This allows for the codebase to be maintained and updated more easily.
```

2023-06-14 15:07 UTC, xelaint commented on docs/styles.md
> +Here's an example of how you might structure the HTML and CSS for a parent component and its child components:
```suggestion
## Example
```

2023-06-14 15:07 UTC, xelaint commented on docs/styles.md
> +<div class="parent-component">
```
<div class="wrapper">
  <div class="component">
    <h3>Title</h3>
    <p>Description</p>
  </div>
  <div class="component">
    <h3>Title</h3>
    <p>Description</p>
  </div>
  <div class="component">
    <h3>Title</h3>
    <p>Description</p>
  </div>
</div>

```

2023-06-14 15:07 UTC, xelaint commented on docs/styles.md
> +.parent-component {
```suggestion
.wrapper {
```

2023-06-14 15:07 UTC, xelaint commented on docs/styles.md
> +  padding: 20px;
remove padding and margin, add

`gap: 16px;`

2023-06-14 15:07 UTC, xelaint commented on docs/styles.md
> +  margin-bottom: 10px;
remove `margin-bottom`

this style is doing what the doc is saying what not to do.

2023-06-14 15:07 UTC, xelaint commented on docs/styles.md
> +.child-component {
```suggestion
.component {
```

2023-06-14 15:07 UTC, xelaint commented on docs/styles.md
> +In this example, the parent component defines the padding and margin for all of its child components. Each child component only defines its own internal padding and margin. This allows the child comp
```suggestion
In this example, the wrapper element sets the gaps between the rows and columns of the components in a flex layout. The inner component defines its own internal padding.
```

2023-07-21 13:35 UTC, closed without merging

2023-07-21 13:36 UTC, damienwebdev commented
@shadow0500 please submit another PR with the requested changes.