Update Readme.md file and tried to make it as comprehensive as much as possible.
graycoreio/daffodil pull request #2470
Opened 2023-06-13 07:47 UTC by shadow0500

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2023-06-13 11:39 UTC, damienwebdev requested changes

2023-06-13 11:39 UTC, damienwebdev commented on docs/styles.md
> +Child components should not define their own outer padding or margin. This is to ensure the component can be reused in other parts of an app. The parent component should define the padding and margin
These changes can be removed from this commit.

2023-06-13 11:39 UTC, damienwebdev commented on tools/builders/guides/fragment-introspection.md
> +**In order for Apollo to properly match fragment types, the GraphQL schema must be fetched, processed, added to the codebase, and loaded into the *`ApolloClient`* cache.**
These changes can be removed from this commit.

2023-06-13 11:39 UTC, damienwebdev commented on libs/analytics/README.md
> +**Before going deep down first we need to understand this technical term so Let's begin with the word *Analytics Action Mapping* so you can easily understand rest of the things.**
I think, instead of a rewording, the entire contents of this README need to be re-written based upon the code within the package.

2023-06-13 14:40 UTC, griest024 requested changes
There are many uses of the first person here. Use the third person narration style instead. So instead of saying `It allows us to track` you might say `It provides a way to track` or `It enables the tracking of`.

2023-06-13 14:40 UTC, griest024 commented on libs/analytics/README.md
> +**Before going deep down first we need to understand this technical term so Let's begin with the word *Analytics Action Mapping* so you can easily understand rest of the things.**
Avoid using the first person in documentation: https://engineering.usu.edu/students/ewc/writing-resources/technical-writing-standards#:~:text=Narration%20(Point%20of%20View)&text=Third%20person%20narration%20is%20most,(common%20in%20business%20correspondence).

2023-06-13 14:40 UTC, griest024 commented on libs/analytics/README.md
> +   - `DaffCategoryLoadSuccess:`This action represents the successful loading of a category page, providing detailed information about the category. It allows us to track the performance and popularit
don't use first person (`us`)

2023-06-14 07:35 UTC, shadow0500 commented
Okay @damienwebdev @griest024 I will take care of it and look into this .
so you are trying to say @damienwebdev I need to write this file according to the whole code or only follow package.json ? Could you please  share the path ?

2023-06-15 00:39 UTC, griest024 commented
@shadow0500 create a feature branch for every different PR. This PR includes way too many unrelated changes. Please familiarize yourself with our [contribution guidelines](https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#submit-pr).

Pay attention to the section about commit messages. The same rules apply to PR titles as those eventually become the merged, squashed commit message.

Please take a look at some of my past PRs as an example.

Closing as too broad

2023-06-15 00:39 UTC, closed without merging

2023-06-15 13:22 UTC, shadow0500 commented
Okay @griest024 , I am sorry for the mess up but I will not do anything wrong from the next time .