feat(core): add subpackage for external scripts
graycoreio/daffodil pull request #2773
Opened 2024-03-28 15:02 UTC by damienwebdev

This adds a new subpackage for loading third-party javascript dynamically in a document. This will likely be useful when interacting with third-party widgets and payment APIs.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information

2024-04-10 21:56 UTC, griest024 requested changes
just one missing doc but otherwise lgtm

2024-04-10 21:56 UTC, griest024 commented on libs/core/external-script/src/script.ts
> +export interface DaffExternalScript {
needs docs

2024-04-23 15:54 UTC, damienwebdev commented on libs/core/external-script/src/script.ts
> +export interface DaffExternalScript {
2f2bd063c30ac315630294652af7e0caca116c68

2024-04-23 16:58 UTC, griest024 approved these changes

2024-04-24 14:17 UTC, merged