fix(external-router): extract daff paths ignoring full path
graycoreio/daffodil pull request #2955
Opened 2024-08-05 21:30 UTC by griest024

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

`daffExtractDaffPathData` ignores all routes in the path except the last, incorrectly building the path when the last route is an empty path route.

## What is the new behavior?
`daffExtractDaffPathData` computes the path from all routes in the path from root.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2024-08-05 21:31 UTC, griest024 commented
@damienwebdev is this the behavior that we actually want?

2024-08-06 19:06 UTC, damienwebdev requested changes

2024-08-06 19:06 UTC, damienwebdev commented on libs/external-router/src/util/extract-daff-path-data.ts
> +  const pathFromRoot = snapshot.pathFromRoot.flatMap((route) => route.url).map((seg) => seg.path).join('/');
What was previously happening? Can you add a test for the prior state that errored? Or, does the associated test cover that state?

2024-08-06 19:08 UTC, griest024 commented on libs/external-router/src/util/extract-daff-path-data.ts
> +  const pathFromRoot = snapshot.pathFromRoot.flatMap((route) => route.url).map((seg) => seg.path).join('/');
the test covers that state

2024-08-07 15:21 UTC, damienwebdev approved these changes
lgtm

2024-08-07 15:21 UTC, merged