docs(newsletter): clean up formatting and verbiage of existing documentation
graycoreio/daffodil pull request #3002
Opened 2024-08-20 15:29 UTC by xelaint

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2024-08-20 15:29 UTC, xelaint commented
@griest024 there seemed to be some duplicating information so I tried my best to clean it up and remove what I thought was redundant information. Can you review and make sure I didn't remove important information?

2024-08-30 17:27 UTC, damienwebdev requested changes

2024-08-30 17:27 UTC, damienwebdev commented on libs/newsletter/README.md
> +npm install @daffodil/newsletter @daffodil/core @ngrx/store @ngrx/effects --save
Remove extraneous packages.

2024-08-30 17:27 UTC, damienwebdev commented on libs/newsletter/README.md
> +yarn add @daffodil/newsletter @daffodil/core @ngrx/store @ngrx/effects
Remove extraneous packages.

2024-08-30 17:27 UTC, damienwebdev commented on libs/newsletter/README.md
> +> After installing, an ecommerce platform driver needs to be set up. We highly recommend installing the [in-memory web api](./guides/drivers.md) for fast, out-of-the-box development.
Remove the "ecommerce" part of this.

2024-08-30 17:27 UTC, damienwebdev commented on libs/newsletter/README.md
> +> After installing, an ecommerce platform driver needs to be set up. We highly recommend installing the [in-memory web api](./guides/drivers.md) for fast, out-of-the-box development.
> We highly recommend installing the [in-memory web api](./guides/drivers.md) for fast, out-of-the-box development.

Should probably be

> We highly recommend installing the [in-memory web api](./guides/drivers.md) for getting started quickly.

2024-08-30 17:27 UTC, damienwebdev commented on libs/newsletter/README.md
> +Check out a [live example](https://stackblitz.com/edit/daff-newsletter-example) of `@daffodil/newsletter` in action!
This demo needs an update desperately.

2024-09-12 12:38 UTC, xelaint commented on libs/newsletter/README.md
> +Check out a [live example](https://stackblitz.com/edit/daff-newsletter-example) of `@daffodil/newsletter` in action!
created an issue for this #3062

2024-09-12 12:38 UTC, xelaint commented on libs/newsletter/README.md
> +> After installing, an ecommerce platform driver needs to be set up. We highly recommend installing the [in-memory web api](./guides/drivers.md) for fast, out-of-the-box development.
updated

2024-09-12 12:39 UTC, xelaint commented on libs/newsletter/README.md
> +> After installing, an ecommerce platform driver needs to be set up. We highly recommend installing the [in-memory web api](./guides/drivers.md) for fast, out-of-the-box development.
removed

2024-09-12 12:39 UTC, xelaint commented on libs/newsletter/README.md
> +yarn add @daffodil/newsletter @daffodil/core @ngrx/store @ngrx/effects
removed

2024-09-12 12:39 UTC, xelaint commented on libs/newsletter/README.md
> +npm install @daffodil/newsletter @daffodil/core @ngrx/store @ngrx/effects --save
removed

2024-09-20 12:32 UTC, merged