feat(eslint): add linting rules for testing
graycoreio/daffodil pull request #3056
Opened 2024-09-11 01:56 UTC by gracetxgao

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

#122

## What is the new behavior?

Maximum describe() depth of 3 set for tests.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2024-09-11 02:14 UTC, damienwebdev commented
This is awesome! @griest024 do you think we should set depth to 4 as warning, and 5 as error? I only see a few with 5, but many more with 3/4.

2024-09-11 13:24 UTC, griest024 requested changes

2024-09-11 13:24 UTC, griest024 commented on .eslintrc.js
> +        ]
This should go in the base config,: `tools/eslint/config/index.js`

2024-09-11 13:25 UTC, griest024 commented
@damienwebdev 5 as an error sounds good. Can we mix error and warning values for the same rule? Afaik eslint does not allow for this.

2024-09-12 17:49 UTC, damienwebdev commented
https://github.com/graycoreio/daffodil/blob/d41bc5a949b1e827e35129ea4c0d449a2a8a7b47/tools/eslint/config/package.json#L14 needs an update for the dependency as well

2024-09-17 03:02 UTC, damienwebdev approved these changes, later dismissed
lgtm. Needs @griest024 approval for merge.

2024-09-17 13:46 UTC, griest024 requested changes

2024-09-17 13:46 UTC, griest024 commented on tools/eslint/config/index.js
> +    ],
Move this under the `custom` section (denoted by the comment). Everything under `ng-cli-compat` and `ng-cli-compat--formatting-add-on` were added to replace deprecated packages and are going to eventually be mass deleted.

2024-09-17 17:23 UTC, griest024 approved these changes, later dismissed
lgtm

2024-09-17 17:24 UTC, griest024 commented
needs a rebase

2024-09-25 13:42 UTC, damienwebdev commented
@gracetxgao Needs another rebase.

2024-12-19 15:52 UTC, damienwebdev approved these changes
lgtm

2024-12-19 15:52 UTC, merged