feat(daffio): add design docs route
graycoreio/daffodil pull request #3113
Opened 2024-09-23 23:07 UTC by griest024

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: #2917 

## What is the new behavior?

## Does this PR introduce a breaking change?
```
[ ] Yes
[ ] No
```

## Other information
#3112 is an issue but shouldn't block this PR

2024-09-24 16:02 UTC, xelaint commented
Top nav should stay the same as the primary `/docs` nav, except `Design` needs to be added as a nav item, which navigates to `docs/design`

- `Examples` is not going to be path that we'll be using.
- `Packages` should be changed to `Components`
- `docs/design` should be a custom page not rendered by a README. It's going to look something like this (I can do the UI for it, just needed the route set up)
<img width="740" alt="Screen Shot 2024-09-24 at 11 57 29 AM" src="https://github.com/user-attachments/assets/66b9eec6-d03b-4d91-bd82-f7c6bfa36fb4">

- The API reference page for each component is going to be displayed in the form of a tab within the component page.
<img width="742" alt="Screen Shot 2024-09-24 at 11 55 44 AM" src="https://github.com/user-attachments/assets/83de9432-43f0-4d0a-b324-c2b75142b10c">

2024-09-24 16:03 UTC, xelaint requested changes
Top nav should stay the same as the primary `/docs` nav, except `Design` needs to be added as a nav item, which navigates to `docs/design`

- `Examples` is not going to be path that we'll be using since all examples will be housed within the overview tab.
- `Packages` should be changed to `Components`
- `docs/design` should be a custom page not rendered by a README. It's going to look something like this (I can do the UI for it, just needed the route set up)
<img width="740" alt="Screen Shot 2024-09-24 at 11 57 29 AM" src="https://github.com/user-attachments/assets/66b9eec6-d03b-4d91-bd82-f7c6bfa36fb4">

- The API reference page for each component is going to be displayed in the form of a tab within the component page.
<img width="742" alt="Screen Shot 2024-09-24 at 11 55 44 AM" src="https://github.com/user-attachments/assets/83de9432-43f0-4d0a-b324-c2b75142b10c">

2024-09-25 18:43 UTC, griest024 commented
@xelaint I've reworked the design docs structure to hopefully match your requirements. Note there are two issues that should be handled in future PRs and not block this one:
- The order of items in the sidebar does not match the design. We need a good pattern for hardcoding tree order and sorting.
- The docs don't have overview/API tabs. In a future PR, add a design for this and I will wire it up.

2024-09-25 20:27 UTC, xelaint requested changes

2024-09-25 20:27 UTC, xelaint commented on apps/daffio/src/app/docs/design/containers/docs-list/docs-list.component.ts
> +  selector: 'daffio-docs-list-container',
should be `daffio-docs-design-list-container`, since `daffio-docs-list-container` is used as the selector in `DaffioDocsListContainer`

2024-09-25 20:59 UTC, griest024 commented on apps/daffio/src/app/docs/design/containers/docs-list/docs-list.component.ts
> +  selector: 'daffio-docs-list-container',
yup, fixed

2024-09-25 21:06 UTC, xelaint commented
> @xelaint I've reworked the design docs structure to hopefully match your requirements. Note there are two issues that should be handled in future PRs and not block this one:
> 
> * The order of items in the sidebar does not match the design. We need a good pattern for hardcoding tree order and sorting.
> * The docs don't have overview/API tabs. In a future PR, add a design for this and I will wire it up.

issues for these have been added, #3123 and #3124

2024-09-26 13:37 UTC, xelaint approved these changes, later dismissed

2024-09-26 14:23 UTC, merged