feat(seo): add support for schema
graycoreio/daffodil pull request #3378
Opened 2024-12-23 22:17 UTC by damienwebdev

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
We do not support [structured data](https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data) in `@daffodil/seo`

Fixes: N/A

## What is the new behavior?
We now support structured data in `@daffodil/seo`

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

2024-12-23 22:19 UTC, damienwebdev commented on libs/seo/router/src/schema/collect-schema.ts
> +	return [...new Set(routes.map((r) => r.data?.daffSeoData?.schema).filter((el) => el))];
Note that this function is unfortunately odd due to https://angular.dev/api/router/RouterConfigOptions#paramsInheritanceStrategy causing multiple instances of the same schema to be merged together.

2024-12-26 19:06 UTC, griest024 requested changes

2024-12-26 19:06 UTC, griest024 commented on libs/seo/src/schema/schema.service.ts
> +export class DaffSchemaService<T> {
Do you think it makes sense for this to implement `DaffSeoRestoreableServiceInterface`? It seems to me that this could benefit from being restoreable.

2024-12-26 19:06 UTC, griest024 commented on libs/seo/router/src/schema/schema.effect.ts
> +	updateSchema$(): Observable<void> {
If we want restorable behavior, this should be implemented with `DaffSeoPageHookRouterEffects`

2024-12-26 19:06 UTC, griest024 commented on libs/seo/router/src/schema/provider.ts
> +export const provideDaffSeoRouterSchema = (): EnvironmentProviders => {
needs docs

2024-12-26 19:06 UTC, griest024 commented on apps/daffio/src/app/content/home/home-routing.module.ts
> +      }
I think `@daffodil/seo` should export a "route with schema" model that types this structure. https://github.com/graycoreio/daffodil/blob/1f1f85482b0d5d5fbdc9c5f5ec5f06ad2ff022cc/libs/router/src/named-view/models/route.type.ts#L8-L12 gives an example of this

2025-01-02 16:09 UTC, damienwebdev commented on libs/seo/src/schema/schema.service.ts
> +export class DaffSchemaService<T> {
I wasn't quite sure. Now that we no longer have redirects for external router, I was thinking that we no longer need the restorability feature.

2025-01-02 16:12 UTC, griest024 commented on libs/seo/src/schema/schema.service.ts
> +export class DaffSchemaService<T> {
IIRC the restoreable feature was to support the back button as well as working around external router jank.

2025-01-02 16:27 UTC, damienwebdev commented on libs/seo/router/src/schema/collect-schema.ts
> +	return [...new Set(routes.map((r) => r.data?.daffSeoData?.schema).filter((el) => el))];
This comment was moved into the codebase.

2025-01-02 16:52 UTC, damienwebdev commented on apps/daffio/src/app/content/home/home-routing.module.ts
> +      }
Added in https://github.com/graycoreio/daffodil/pull/3378/commits/c928127f7dc23bcaa9c9b947f3e832532a683179#diff-70e0158a71af90d22afa817f09a45c62d966c958b59786d2757064bb84e0e2ebR10

2025-01-02 16:52 UTC, damienwebdev commented on libs/seo/router/src/schema/provider.ts
> +export const provideDaffSeoRouterSchema = (): EnvironmentProviders => {
Added in https://github.com/graycoreio/daffodil/pull/3378/commits/c928127f7dc23bcaa9c9b947f3e832532a683179

2025-01-02 16:53 UTC, damienwebdev commented on libs/seo/router/src/schema/schema.effect.ts
> +	updateSchema$(): Observable<void> {
I'm not certain we need this.

2025-01-02 20:31 UTC, damienwebdev commented on libs/seo/src/schema/schema.service.ts
> +export class DaffSchemaService<T> {
After playing around with https://github.com/graycoreio/daffodil/pull/3378/files#diff-1fc5438c7a4061aa58ededc41b423ba0be76457ef0a529ef031a373f229e21b5 I do not believe the restoration. behavior is relevant any longer.

2025-01-03 16:59 UTC, griest024 approved these changes, later dismissed
seems you have to fix tests in external router but otherwise lgtm

2025-01-03 21:03 UTC, damienwebdev commented
@griest024 this is resolved.

2025-01-03 21:35 UTC, griest024 approved these changes, later dismissed

2025-01-06 19:51 UTC, merged