feat(design): add input component
graycoreio/daffodil pull request #3381
Opened 2024-12-27 21:59 UTC by gracetxgao

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: #416 

## What is the new behavior?
Adds input component.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

2024-12-30 16:59 UTC, xelaint requested changes

2024-12-30 16:59 UTC, xelaint commented on libs/design/src/atoms/form/form-field/form-field/form-field.component.html
> +    <ng-content select=".prefix"></ng-content>
prefix and suffix should not be selected using the class, and the whole span class will not be needed either. We have the `DaffPrefixDirective` and `DaffSuffixDirective` that can be used via `ContentChild`.

Check the button or notification component for implementation example.

2024-12-30 16:59 UTC, xelaint commented on libs/design/src/atoms/form/form-field/form-field/form-field.component.html
> +		*ngIf="_control.controlType === 'native-select'"
Move this logic into the component

2024-12-30 16:59 UTC, xelaint commented on libs/design/src/atoms/form/form-field/form-field/form-field.component.html
> +}
`hint` should be added as a `<ng-content>` outside of `daff-form-field__control`

2025-01-02 14:37 UTC, xelaint commented on libs/design/src/atoms/form/form-field/form-field/form-field.component.html
> +@if (_control?.ngControl?.touched) {
@damienwebdev is it up to the form field component to enforce this?

2025-02-03 15:02 UTC, xelaint commented
@damienwebdev this is blocking #2467 and requires a review from you.

2025-05-06 17:49 UTC, damienwebdev submitted a review, later dismissed
lgtm

2025-05-06 17:49 UTC, xelaint submitted a review, later dismissed

2025-05-06 19:34 UTC, merged