feat(design): create native select component
graycoreio/daffodil pull request #3383
Opened 2024-12-27 22:05 UTC by gracetxgao

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/graycoreio/daffodil/blob/develop/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Fixes: #416 

## What is the new behavior?
Starts native select component, not completely finished.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This branch depends on `dropdown-component` (#2458) and `gracetxgao/textarea-component` (#3382)

2025-08-25 15:31 UTC, xelaint commented
@damienwebdev ready for review

2025-09-23 14:54 UTC, damienwebdev requested changes

2025-09-23 14:54 UTC, damienwebdev commented on libs/design/src/atoms/form/native-select/native-select.component.scss
>  	box-shadow: none;
On a dark-theme, the option is invisible:

<img width="732" height="287" alt="Image" src="https://github.com/user-attachments/assets/a152b83b-e3dd-4b6d-bf37-4c4bf41f21eb" />

2025-09-23 14:54 UTC, damienwebdev commented on libs/design/src/atoms/form/native-select/native-select.component.ts
> +    @Optional() private formField: DaffFormFieldComponent,
Can you add a comment here explaining that the `@Optional()` is intentional so that we control the error message? I can imagine revisiting this in the future and forgetting that,

2025-09-23 15:19 UTC, xelaint commented on libs/design/src/atoms/form/native-select/native-select.component.scss
>  	box-shadow: none;
<img width="1026" height="810" alt="Screen Shot 2025-09-23 at 11 19 04 AM" src="https://github.com/user-attachments/assets/ccd57604-56a0-47ca-a561-e5c0c5a8a58e" />

This is what I have.

2025-09-23 15:21 UTC, xelaint commented on libs/design/src/atoms/form/native-select/native-select.component.ts
> +    @Optional() private formField: DaffFormFieldComponent,
done

2025-09-23 15:47 UTC, xelaint commented on libs/design/src/atoms/form/native-select/native-select.component.scss
>  	box-shadow: none;
updated w/ theming support for `<option>`

2025-09-23 17:08 UTC, damienwebdev approved these changes
lgtm

2025-09-23 17:09 UTC, merged